### ISSUE TITLE
Paper submission checklist

### ISSUE THREAD

**Issue by huddlej** [blab/measurements-panel#1]
The following items need to be completed prior to paper submission:

- [x] Add code to produce Figure 1 (@huddlej)
- [x] Add annotated screenshot of the tool as it is in Auspice for Figure 2 (@joverlee521)
- [x] Write text for Results 3.1 about tool use cases (@joverlee521)
- [x] Figure 3 -> Results 3.2 -> Create composite of tree annotated by important date ranges (vaccine selection date vs. afterwards), two views of the measurements panel, plus maybe frequencies (@jameshadfield)
- [x] Write text for Results 3.2 case study about vaccine strain selection (@jameshadfield and @huddlej)
- [x] Figure 4 -> Results 3.3 -> composite of three measurement panels plus inset of tree context for the clade and the reference strains (@jameshadfield)
	* Color inset tree with strain names by genotype
- [x] Write text for Results 3.3 case study about genotype-specific patterns in titer data (@jameshadfield and @huddlej)
- [x] Edit methods down to 1pp of design decisions (@huddlej)
- [x] Add 1pp on data curation (@huddlej)
- [x] Add 1pp on implementation on data and code for measurements panel (@joverlee521)
- [x] Edit intro down to minimal scientific background needed to understand figures and case studies (@huddlej)
- [x] Add funding sources
- [x] Write acknowledgements
- [x] Write discussion
	* 1pp importance of this tool for vaccine selection
	* 1pp importance more broadly outside of academia
	* 1pp potential for expanding to other datasets like DMS
- [x] Write data availability statement
- [x] Add supplemental table with GISAID and INSDC accessions with authors
- [x] Choose keywords (min: 5, max: 8)
